-- Active: 1776155129190@@127.0.0.1@5432@postgres@public
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

-- Buat database

-- Buat skema
CREATE SCHEMA IF NOT EXISTS ngabengkel AUTHORIZATION postgres;

DO $$
BEGIN
-- Buat role untuk ENUM user_role
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('admin', 'customer');
    END IF;
END
$$;


BEGIN;

CREATE TABLE IF NOT EXISTS ngabengkel.bookings
(
    booking_id character(36) COLLATE pg_catalog."default" NOT NULL,
    user_id character(36) COLLATE pg_catalog."default",
    kendaraan_id character(36) COLLATE pg_catalog."default",
    eta timestamp without time zone,
    keluhan_awal text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    alasan_tolak text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bookings_pkey PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.chat
(
    message_id character(36) COLLATE pg_catalog."default" NOT NULL,
    wo_id character(36) COLLATE pg_catalog."default",
    sender_id character(36) COLLATE pg_catalog."default",
    pesan text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_pkey PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.inventory_items
(
    inventory_id character(36) COLLATE pg_catalog."default" NOT NULL,
    tipe character varying(20) COLLATE pg_catalog."default",
    nama character varying(100) COLLATE pg_catalog."default",
    kode_part character varying(50) COLLATE pg_catalog."default",
    merek character varying(50) COLLATE pg_catalog."default",
    kompatibilitas text COLLATE pg_catalog."default",
    satuan character varying(20) COLLATE pg_catalog."default",
    stok integer,
    harga_satuan numeric(10, 2),
    CONSTRAINT inventory_items_pkey PRIMARY KEY (inventory_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.kendaraan
(
    kendaraan_id character(36) COLLATE pg_catalog."default" NOT NULL,
    user_id character(36) COLLATE pg_catalog."default",
    merek character varying(50) COLLATE pg_catalog."default",
    model character varying(50) COLLATE pg_catalog."default",
    tahun smallint,
    nomor_polisi character varying(20) COLLATE pg_catalog."default",
    warna character varying(30) COLLATE pg_catalog."default",
    nomor_rangka character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT kendaraan_pkey PRIMARY KEY (kendaraan_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.mekaniks
(
    mekanik_id character(36) COLLATE pg_catalog."default" NOT NULL,
    nama character varying(100) COLLATE pg_catalog."default",
    telepon character varying(20) COLLATE pg_catalog."default",
    keahlian character varying(100) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT mekaniks_pkey PRIMARY KEY (mekanik_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.queue
(
    queue_id character(36) COLLATE pg_catalog."default" NOT NULL,
    wo_id character(36) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT queue_pkey PRIMARY KEY (queue_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.slots
(
    slot_id character(36) COLLATE pg_catalog."default" NOT NULL,
    nomor_slot character varying(10) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    wo_id character(36) COLLATE pg_catalog."default",
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT slots_pkey PRIMARY KEY (slot_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.transactions
(
    transaction_id character(36) COLLATE pg_catalog."default" NOT NULL,
    wo_id character(36) COLLATE pg_catalog."default",
    total_biaya numeric(10, 2),
    metode_pembayaran character varying(50) COLLATE pg_catalog."default",
    tanggal_bayar timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.users
(
    user_id character(36) COLLATE pg_catalog."default" NOT NULL,
    nama character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    telepon character varying(20) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    fcm_token character varying(255) COLLATE pg_catalog."default",
    role user_role,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.wo_items
(
    wo_item_id character(36) COLLATE pg_catalog."default" NOT NULL,
    wo_id character(36) COLLATE pg_catalog."default",
    inventory_id character(36) COLLATE pg_catalog."default",
    nama_item character varying(100) COLLATE pg_catalog."default",
    jumlah integer,
    harga_satuan numeric(10, 2),
    subtotal numeric(10, 2),
    CONSTRAINT wo_items_pkey PRIMARY KEY (wo_item_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.wo_progress
(
    progress_id character(36) COLLATE pg_catalog."default" NOT NULL,
    wo_id character(36) COLLATE pg_catalog."default",
    deskripsi text COLLATE pg_catalog."default",
    tipe character varying(20) COLLATE pg_catalog."default",
    foto_url character varying(255) COLLATE pg_catalog."default",
    est_biaya_tambahan numeric(10, 2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wo_progress_pkey PRIMARY KEY (progress_id)
);

CREATE TABLE IF NOT EXISTS ngabengkel.work_orders
(
    wo_id character(36) COLLATE pg_catalog."default" NOT NULL,
    nomor_wo character varying(20) COLLATE pg_catalog."default",
    user_id character(36) COLLATE pg_catalog."default",
    kendaraan_id character(36) COLLATE pg_catalog."default",
    booking_id character(36) COLLATE pg_catalog."default",
    mekanik_id character(36) COLLATE pg_catalog."default",
    deskripsi_kerusakan text COLLATE pg_catalog."default",
    estimasi_biaya numeric(10, 2),
    biaya_jasa numeric(10, 2),
    status character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT work_orders_pkey PRIMARY KEY (wo_id)
);

ALTER TABLE IF EXISTS ngabengkel.bookings
    ADD CONSTRAINT bookings_kendaraan_id_fkey FOREIGN KEY (kendaraan_id)
    REFERENCES ngabengkel.kendaraan (kendaraan_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.bookings
    ADD CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES ngabengkel.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.chat
    ADD CONSTRAINT chat_sender_id_fkey FOREIGN KEY (sender_id)
    REFERENCES ngabengkel.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.chat
    ADD CONSTRAINT chat_wo_id_fkey FOREIGN KEY (wo_id)
    REFERENCES ngabengkel.work_orders (wo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.kendaraan
    ADD CONSTRAINT kendaraan_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES ngabengkel.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.queue
    ADD CONSTRAINT queue_wo_id_fkey FOREIGN KEY (wo_id)
    REFERENCES ngabengkel.work_orders (wo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.slots
    ADD CONSTRAINT slots_wo_id_fkey FOREIGN KEY (wo_id)
    REFERENCES ngabengkel.work_orders (wo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.transactions
    ADD CONSTRAINT transactions_wo_id_fkey FOREIGN KEY (wo_id)
    REFERENCES ngabengkel.work_orders (wo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.wo_items
    ADD CONSTRAINT wo_items_inventory_id_fkey FOREIGN KEY (inventory_id)
    REFERENCES ngabengkel.inventory_items (inventory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.wo_items
    ADD CONSTRAINT wo_items_wo_id_fkey FOREIGN KEY (wo_id)
    REFERENCES ngabengkel.work_orders (wo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.wo_progress
    ADD CONSTRAINT wo_progress_wo_id_fkey FOREIGN KEY (wo_id)
    REFERENCES ngabengkel.work_orders (wo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.work_orders
    ADD CONSTRAINT work_orders_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES ngabengkel.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.work_orders
    ADD CONSTRAINT work_orders_kendaraan_id_fkey FOREIGN KEY (kendaraan_id)
    REFERENCES ngabengkel.kendaraan (kendaraan_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.work_orders
    ADD CONSTRAINT work_orders_mekanik_id_fkey FOREIGN KEY (mekanik_id)
    REFERENCES ngabengkel.mekaniks (mekanik_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ngabengkel.work_orders
    ADD CONSTRAINT work_orders_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES ngabengkel.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;